config/routes.rb
Rails.application.routes.draw do
  root to: 'schedules#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  devise_for :admin_users, controllers: {
    sessions: 'admin_users/sessions',
    passwords: 'admin_users/passwords',
    registrations: 'admin_users/registrations'
  }

  # resources :users, only: [:edit, :update]

  resources :schedules do
    resources :comments, only: :create
  end
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  with_options presence: true do
    validates :title
    validates :start_time
    validates :end_time
    validates :place
    validates :info
  end

  belongs_to :user, optional: true
  belongs_to :admin_user, optional: true
  has_many :comments, dependent: :destroy
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def index
    @schedules = Schedule.all
  end

  def new
    @schedule = Schedule.new
  end

  def create
    @schedule = Schedule.new(schedule_params)
    if @schedule.save
      redirect_to root_path(@schedule)
    else
      render new_schedule_path
    end
  end 

  def show
    @schedule = Schedule.find(params[:id])
    @comment = Comment.new
    @comments = @schedule.comments.includes(:user)
  end

  def edit
    @schedule = Schedule.find(params[:id])
  end

  def update
    @schedule = Schedule.find(params[:id])
    if @schedule.update(schedule_params)
      redirect_to schedules_path
    else
      render :edit
    end
  end

  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy
    redirect_to root_path
  end

  private

  def schedule_params
    if user_signed_in?
      params.require(:schedule).permit(:title, :start_time, :end_time, :place, :info).merge(user_id: current_user.id)
    else
      params.require(:schedule).permit(:title, :start_time, :end_time, :place, :info).merge(admin_user_id: current_admin_user.id)
    end
  end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/edit.html.erb
<%= form_with model: @schedule, url: schedule_path, local: true do |f| %>
  <%= render 'shared/error_messages', model: f.object %>

  タイトル
  <%= f.text_area :title, placeholder:"例 サッカー、スイミングなど", maxlength:"20" %>

  <p>開始日
  <%= f.datetime_select(:start_time, use_month_numbers: true, discard_year: true, selected: Date.today.year, prompt:'--', datetime_separator: '開始時間')%></p>

  <p>終了日
  <%= f.datetime_select(:end_time, use_month_numbers: true, discard_year: true, selected: Date.today.year, prompt:'--', datetime_separator: '終了時間')%></p>
  
  <p>場所
  <%= f.text_area :place, placeholder:"例 ○○小学校、××グラウンドなど", maxlength:"20" %></p>

  <p>活動内容
  <%= f.text_area :info, placeholder:"詳細を記入" %></p>

  <%= f.submit "予定を変更する" %>
  <p><%= link_to "カレンダーに戻る", root_path %></p>
<% end %>

app/views/schedules/index.html.erb
<% if user_signed_in? %>
  <h1><%= "#{current_user.name}のカレンダー" %></h1>
  <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
  <%= link_to "新しい予定を作成", new_schedule_path %>

  <%= month_calendar events: @schedules do |date, schedules| %>
    <%= date.day %><br>
    <% schedules.each do |schedule| %>
      <% if current_user.id == schedule.user_id || schedule.user_id == nil %>
        <li><%= link_to schedule.title, schedule_path(schedule.id) %></li>
      <% end %>
    <% end %>
  <% end %>
<% elsif admin_user_signed_in? %>
  <h1><%= "#{current_admin_user.name}のカレンダー" %></h1>
  <%= link_to 'ログアウト', destroy_admin_user_session_path, method: :delete %>
  <%= link_to "新しい予定を予定", new_schedule_path %>

  <%= month_calendar events: @schedules do |date, schedules| %>
    <%= date.day %><br>
    <% schedules.each do |schedule| %>
      <li><%= link_to schedule.title, schedule_path(schedule.id) %></li>
    <% end %>
  <% end %>
<% else %>
  <%= link_to "新規ユーザー登録", new_user_registration_path %>
  <%= link_to "ユーザー用ログイン", new_user_session_path %><br />
  <%= link_to "新規管理者登録", new_admin_user_registration_path %>
  <%= link_to "管理者用ログイン", new_admin_user_session_path %>
<% end %>

app/views/schedules/new.html.erb
<%= form_with model: @schedule, url: schedules_path, local: true do |f| %>
  <%= render 'shared/error_messages', model: f.object %>

  タイトル
  <%= f.text_area :title, placeholder:"例 サッカー、スイミングなど", maxlength:"20" %>

  <p>開始日
  <%= f.datetime_select(:start_time, use_month_numbers: true, discard_year: true, selected: Date.today.year, prompt:'--', datetime_separator: '開始時間')%></p>

  <p>終了日
  <%= f.datetime_select(:end_time, use_month_numbers: true, discard_year: true, selected: Date.today.year, prompt:'--', datetime_separator: '終了時間')%></p>
  
  <p>場所
  <%= f.text_area :place, placeholder:"例 ○○小学校、××グラウンドなど", maxlength:"20" %></p>

  <p>活動内容
  <%= f.text_area :info, placeholder:"詳細を記入" %></p>

  <%= f.submit "予定を登録する" %>
  <p><%= link_to "カレンダーに戻る", root_path %></p>
<% end %>

app/views/schedules/show.html.erb
<h1>タイトル</h1>
<%= @schedule.title %>

<h3>開始日時</h3>
<%= @schedule.start_time.strftime("%m/%d(#{%w(日 月 火 水 木 金 土)[@schedule.created_at.wday]}) %H:%M") %>

<h3>終了日時</h3>
<%= @schedule.end_time.strftime("%m/%d(#{%w(日 月 火 水 木 金 土)[@schedule.created_at.wday]}) %H:%M") %>

<h3>場所</h3>
<%= @schedule.place %>

<h3>内容</h3>
<%= @schedule.info %>

<h3>コメント欄</h3>
<ul>
  <% @comments.each do |comment| %>
  <li>
    <%= comment.text %>
    <% if comment.admin_user_id == nil %>
      <%= comment.user.name %><%= comment.created_at.strftime("%m/%d(#{%w(日 月 火 水 木 金 土)[comment.created_at.wday]}) %H:%M") %>
    <% else %>
      <%= comment.admin_user.name %><%= comment.created_at.strftime("%m/%d(#{%w(日 月 火 水 木 金 土)[comment.created_at.wday]}) %H:%M") %>
    <% end %>
  </li>
  <% end %>
</ul>

<%= form_with model: [@schedule, @comment], local: true do |f|%>
<%= render 'shared/error_messages', model: f.object %>
  <%= f.text_field :text %>
  <%= f.submit "送信する" %>
<% end %>

<% if user_signed_in? %>
  <% if current_user.id == @schedule.user_id %>
    <p><%= link_to "予定の変更", edit_schedule_path(@schedule), method: :get %></p>
    <p><%= link_to "予定を削除する", schedule_path(@schedule), method: :delete %></p>
  <% end %>
<% else admin_user_signed_in? %>
  <% if current_admin_user.id == @schedule.admin_user_id %>
    <p><%= link_to "予定の変更", edit_schedule_path(@schedule), method: :get %></p>
    <p><%= link_to "予定を削除する", schedule_path(@schedule), method: :delete %></p>
  <% end %>
<% end %>

<p><%= link_to "カレンダーに戻る", root_path %></p>